### ISSUE TITLE
Broken by Campus DLC update

### ISSUE THREAD

**Issue by cieran84** [cerebellum42/BuildingAIChanger#4]
Hey. The Campus update seems to have broken the PrefabAI dropdown menu in Asset Editor. Haven been unsuccessful at trying to unsubscribe/resubscribe, and others have noted the same issue on the workshop comments. Hoping it can get fixed – must have mod!

**Comment by stkfd** [comment]
I will have a look at it soon, however expect it to take a few days until I get to it - pretty busy at the moment and I'll have to set up the dev environment for CSL mods on my current system before starting. It's been a long time since I've worked on anything modding related

**Comment by stkfd** [comment]
Fixed (finally)
